
--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from startup_final_dataset1
group by gender


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from startup_final_dataset1 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from startup_final_dataset1)


-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from startup_final_dataset1
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from startup_final_dataset1
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM startup_final_dataset1
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM startup_final_dataset1
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM startup_final_dataset1)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM startup_final_dataset1
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM startup_final_dataset1
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM startup_final_dataset1
GROUP BY age_group
ORDER BY total_revenue desc;

--Q11. Do frequent buyers spend more?
select 
	purchase_frequency_days, round(avg(purchase_amount),2) as avg_spend,
	count(*) as customers
from startup_final_dataset1
group by purchase_frequency_days  
order by purchase_frequency_days 

--Q12. Which age group spends the most per order?
SELECT 
  age_group,
  ROUND(AVG(purchase_amount),2) AS avg_spend
FROM startup_final_dataset1
GROUP BY age_group
ORDER BY avg_spend DESC;

--Q13. Are frequent buyers more loyal?
SELECT 
  purchase_frequency_days,
  COUNT(*) FILTER (WHERE previous_purchases > 5) AS loyal_customers,
  COUNT(*) AS total_customers
FROM startup_final_dataset1
GROUP BY purchase_frequency_days
ORDER BY purchase_frequency_days;

--Q14. Which age group has highest repeat customers?
SELECT 
  age_group,
  COUNT(*) FILTER (WHERE previous_purchases > 1) AS repeat_customers,
  COUNT(*) AS total_customers
FROM startup_final_dataset1
GROUP BY age_group;

--Q15. Do subscribers purchase more frequently?
SELECT 
  subscription_status,
  ROUND(AVG(purchase_frequency_days),2) AS avg_frequency_days
FROM startup_final_dataset1
GROUP BY subscription_status;

--Q16. Which frequency group generates most revenue?
SELECT 
  purchase_frequency_days,
  SUM(purchase_amount) AS revenue
FROM startup_final_dataset1
GROUP BY purchase_frequency_days
ORDER BY revenue DESC;

--Q17. Who are high-value customers?
SELECT 
  customer_id,
  SUM(purchase_amount) AS total_spent,
  COUNT(*) AS total_orders
FROM startup_final_dataset1
GROUP BY customer_id
ORDER BY total_spent DESC
LIMIT 10;

--Q18. Do frequent buyers depend on discounts?
SELECT 
  purchase_frequency_days,
  discount_applied,
  COUNT(*) AS total_orders
FROM startup_final_dataset1
GROUP BY purchase_frequency_days, discount_applied;
